### PR TITLE
Changed the routes addresses so they are consistent and modified status code for POST to 201

### PR DESCRIPTION
**Pull request by papa28x4**

### CODE REVIEW

**Comment by Kvngston** [comment]
I already made this specific and distinct and swagger documentation has been done on it too, nice idea tho,

**Comment by papa28x4** [comment]
Okay, If you say so. But the right status code for post is 201. Secondly, I didn't see logic in
Following this route to get the user
```
router.put('/user/:id', catchErrors(userController.updateUser));
//Get Specific User
router.get('/user/:id', catchErrors(userController.getUser));
```
and then following a different route to get that user's firstname or lastname
//Get Last Name
router.get('/users/:id/lastname', catchErrors(userController.getUserLastName));
//Set Last Name
router.put('/users/:id/lastname', catchErrors(userController.setUserLastname));

**Comment by goodhands** [comment]
@Kvngston who is working on the swagger documentation? Please loop me in.

Do you mean you have already done the same thing he did here? I believe this is the correct pattern, `users/:id` & `users/:id/firstname`

For reference: https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/

**Comment by Kvngston** [comment]
@goodhands I'm doing documentation and I made each endpoint a little bit more specific for the swagger.

**Comment by Kvngston** [comment]
I will push my change soon

**Comment by Kvngston** [comment]
And it follows that pattern but not exactly that

**Comment by goodhands** [comment]
@Kvngston okay, I'll merge this one then.

**Pull request merged**
